// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhm1s0ASlJI7kOTYIreA88vx2LHsiepKU',
    appId: '1:345861978832:web:affc257180013ac7f97cd5',
    messagingSenderId: '345861978832',
    projectId: 'tko-loyalty-405e2',
    authDomain: 'tko-loyalty-405e2.firebaseapp.com',
    storageBucket: 'tko-loyalty-405e2.firebasestorage.app',
    measurementId: 'G-2X81XGPV8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcVdKEleSw5naZ-K28NIea7o_oSquIieE',
    appId: '1:345861978832:android:55e92bce0791819df97cd5',
    messagingSenderId: '345861978832',
    projectId: 'tko-loyalty-405e2',
    storageBucket: 'tko-loyalty-405e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu2bYX7P3EA9UPb9aETb0HdzeAllJ08RY',
    appId: '1:345861978832:ios:a7399358ceb336f9f97cd5',
    messagingSenderId: '345861978832',
    projectId: 'tko-loyalty-405e2',
    storageBucket: 'tko-loyalty-405e2.firebasestorage.app',
    androidClientId: '345861978832-hlp09lgdb6f4k0f8gmiopnqeh20d0ns2.apps.googleusercontent.com',
    iosClientId: '345861978832-corss5fcnlstlrrhshrahtv02brth2po.apps.googleusercontent.com',
    iosBundleId: 'com.example.tkoToy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu2bYX7P3EA9UPb9aETb0HdzeAllJ08RY',
    appId: '1:345861978832:ios:a7399358ceb336f9f97cd5',
    messagingSenderId: '345861978832',
    projectId: 'tko-loyalty-405e2',
    storageBucket: 'tko-loyalty-405e2.firebasestorage.app',
    androidClientId: '345861978832-hlp09lgdb6f4k0f8gmiopnqeh20d0ns2.apps.googleusercontent.com',
    iosClientId: '345861978832-corss5fcnlstlrrhshrahtv02brth2po.apps.googleusercontent.com',
    iosBundleId: 'com.example.tkoToy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhm1s0ASlJI7kOTYIreA88vx2LHsiepKU',
    appId: '1:345861978832:web:37f2686984561383f97cd5',
    messagingSenderId: '345861978832',
    projectId: 'tko-loyalty-405e2',
    authDomain: 'tko-loyalty-405e2.firebaseapp.com',
    storageBucket: 'tko-loyalty-405e2.firebasestorage.app',
    measurementId: 'G-JHTR1WBGJD',
  );
}
